name: Code checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      # `npm ci` in fact runs `npm prepare` which in turn runs our static checks
      - name: Install dependencies & run static checks
        run: npm ci
